apiVersion: batch/v1
kind: Job
metadata:
  name: minio-init-setup
  namespace: storage
spec:
  ttlSecondsAfterFinished: 120
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: mc
        image: quay.io/minio/mc:latest
        env:
        - name: MINIO_ROOT_USER
          valueFrom:
            secretKeyRef:
              name: minio-credentials
              key: MINIO_ROOT_USER
        - name: MINIO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: minio-credentials
              key: MINIO_ROOT_PASSWORD
        command:
        - sh
        - -c
        - |
          mc alias set local http://minio.storage.svc.cluster.local:9000 $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD &&
          mc mb --ignore-existing local/warehouse &&
          mc mb --ignore-existing local/staging &&
          mc mb --ignore-existing local/mlflow