---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-credentials
  namespace: storage
spec:
  encryptedData:
    MINIO_ROOT_PASSWORD: AgCBrNhiR53OlIUQbGNFJgUmDcKM4JcJfkOt7U52MwMM77urpJ9qDRCW1gOvUx5FRuF4hsOgLeTTqFXRYkWKncyl0E2CA9EAAQpgg6ROxJTgeL0jS4PjjLZSSmJ+xnbjkkRZdYf498zXqNs7pWeMWQw33rUu0C/MfXzANqAVplx4MqgWDoVKRWGKturVATIe60Xf4qhTkpu/w5dwoHbzWWJYy36lpGYkqY+UFaAG2IYTy233kne+giJphkpaZImej9b0kc1azNVaa8htVatiVUlaOOei6MlsPd+pZy3KRyJdkCPW/Gv0D3wHy8UDS/hrDS58+39Yt6XUS1f7Zl+9BOCxgztLl5TC4ht0bjXF5vPTthaRZ3EK6eoD/CcLTob63LUNR3Zf+407On2uVCFWP8HdAeqS5YZ86w+ZlZ5bq5KKHz6S3AnfFMo+iURQNtj1YB2nekCwx+2Jmu7i/Yk86fWjeTh5oKneCV5Oh5yFU8BHoztzb8e+n7G+j9lrgLkmX2U+fV00jVbNbxxztdJdxJkjp9E/LT/VsmML/BbPKEFhJXbKWweq1dkkICRFDFBgIVHgBOVc1nyVe2oX/GRKUhekHj8+c3xNZyF/VrmXyciGFIPkjhWnarxTrYUn0oQTBNBTLoEdxFdoW4TEZRPgXQc+W19oELIZFs+FzJLLjOXmG3x7yqMouMAKJ4iAMa3Jl4rxjjr8L8ENng==
    MINIO_ROOT_USER: AgAL05LpKMcLMbl/Lho68UcamamcC14uxh+eIn11fNU9MKIUF1ZP0zZc9aTLzJwizoqe5mOpU2J/mg3Js9tDyTV48QK12JWMyfxCvwgaszpXHD2XJvmf5FTQhLuaOJZ3gKE022p+Xs0GCOVYvCVLWlnbSVM2xM4YkTbRqmXu8kv1Oj+xCU5jLacT8JcgcOqli0b1tlIxPQQYzNy70y6u+R709h+ADFYB1L4ReVutTr3+Sajd8oNwdeieUH837eEjdxD+ti3Q+TqjMiz4UbHz0Rc4VSopiYQXs3w9FLQhakv1uz7sYBNbeH1+NDVsezLsbAB6BXGm2okWIJf4l/5iT1w6NlBXDMaJjZ4MtYOEjjrysA5MppSdyC2X5GNwv/uwet0Y3o8bP5t2PQFtp3P/WPOIhgUFkqGFgYOsVy+n7+ym0XBmYRjnS35JqBIQ0ls6BNOZUK9nsLbzM2E4bHUJQ9DZe/M5Cwu1dSqdE/9eW2OOq7XlqwrPN/TgnVuL1p0ARpEzI9dSVsKIh6d7Nzl7kdQOmL4ThKt8elFvj2t7ge1SZJX3OXNpEI4JnJyLcHiP0kGZxJ2ywTS6f4gQuDOxh4qkLXO/Bvz/R2/X2DIO/pYPQxLkT7jiAWjlQgWKfrB+DAnYrT9BUbX/dHddWQxsRWI44SqOq9Qmiuwr83VbwHESIWVC561qe9NF4nB2B0obGdnHsCE8ag==
  template:
    metadata:
      name: minio-credentials
      namespace: storage
