---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dremio-credentials
  namespace: query
spec:
  encryptedData:
    access-key: AgBcDZONb+SLPzpsteam3XqTL9gonxHroyLXHEsju/10qIn2d4ze213rPr0Paq88xvVqQp8edtzUf2yLpWsAAs/TsR3hytTbe7V//5lUR69LUfJpzHcXs7AEXkNLPhp/uSFM43DG0ACjTW+tce58CzFMnT3rHicxSdTF2tYKURF6Wk5IaX96QrSPZxwonOQP1bn0/iSr1hOZWuR3HMOy3aDg3ZnNZM4UJQXzpgFrKyCX1VsxqkQbDCu25X0ctoZBbH8OykJ2ZhKXxEZ7tFXKiEzsxyWz9uvmfa3zIdCeFxgiwtmP3YRed0yZNh7fhjcmeBNAYmHykTvtmznKTqio6SXsQqHY9cld/Sk2YO6gWARVoPbARk/aTVhu/m1W+BI23MjzMmjoq4v4HeX7UAdsnUx7loTghRR0EFrRQMLjsT5JijJMiYi2hlwye5n1toxnGz2LlnqyGhi6d4V02jCfcDDBDMO+FL5mzlhLALtMBxOINebyfWR4Dq4SAS8TxhxI8CkAyRFUXMWaE2TmKIeVBXbTPH8v0aLBo7lU+qeKP27Iq15FkLwQNuAbjMFeSih8yemQbiwjKTUT1plmlosYW8KDIFsLLzpjvo3BgSQyGIwZ78PdqpH0CXF3p4yPSh/GcQl75FP1ua5v6CEvfFJiLA/ybBEZ4dESuhaWoVoJj4OPYgHk63Z83NtVxkELhQWV570CRSrb9Q==
    secret-key: AgCD4bT6oW8H7NXBLTD+8mCOSuAf/xvOC7NSc9uhEtKndD+ruQuR3ropC2UgBHloU57iROv8cc6RUEUiWU88U2QhLj5yLnzHT72/6Y+/+FuGHjJpg+Yy5gfrRb4kR+DaB3iLCqHz/Ba3A2bKMy7kUCG+/q233UEGSKtI/1/cZs1Oph+61wVjHSaZsNKVGABNmE/RYYpBhhvjv7KP4mAbxSyX65ujB9aD89Xk51xI2Qp4uRMXR7kPcyyAR+1wpFnUkLSxH6bS5P7EX33V4wlIasq5RJZCYnQmURh4xbJibmblZ2WQAwe7d020rDRf3t7S2Q9zAJKAnBz/Z51XLLnJdDkv29DrjX13lCyvv9mkpXmC+uosURLPcfhy6tGWHHlsi75cmcZHcsWTiM+IDIBjqnHV5tkjWXE+1Bxs6nS5ShbKZj9JWziR47knJ0Wafue0oR7C+70y+/v4lrBtLbfnyoE5dLsCbinM+vuvKQfVcPfH2Ji4SnC97/HiS7sxDbUbCmZ6lsYPP+mqqElI50DUS3j3WEVankAWocXmsQorR3hvlUPVZGkLNadJOlDhTDg3lHtv80xEsMhlzSGk0as2/vlnRxZpUk/pl6hzN118z2vR4PpbhSZpXhyBWX+Q7pzIkpLRqyZeTNnRPTNVR0J6gy3/aXTAVpf03N9y3wFVKtu6ofbUyVEnJpWszS7I7GqsNewOtb5cZZxFtA==
  template:
    metadata:
      name: dremio-credentials
      namespace: query
