apiVersion: v1
kind: Service
metadata:
  name: spark-connect
  namespace: spark
spec:
  selector:
    app: spark-connect
  ports:
  - name: grpc
    port: 15002
    targetPort: 15002
  - name: ui
    port: 4040
    targetPort: 4040