---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: spark-credentials
  namespace: spark
spec:
  encryptedData:
    access-key: AgAmBWJkbRcNZ+CqFOgjVLn5g3ZIQ5XFzylojzJXnqIFZjlCiQu1iLuMbiDYJKS6jJI2sjAtHUsKzxEpttsWUmT5fBK52qC9T8XzMZXgyDTH5XjWILxVFK+lnSrvAalOj0s5nw2dsxgcmpW8avzHe1ezhZZPYUlSUXuJ+nzzL5fkHgDCtEWdatS0aXiyooJLqHw7f+kdXQtc4/Is2aVYDLj7ivHVz/5ASCAFTZ0ka13x5KMCoRQ9ix6C54VA2ia8YyneW2AcYAn+KkivX0Ah83oSWIvBsxPwLHZkKDJRSvkyrNrfEGPM3awRRqms4QuZI/T9d640kGQfJGr6kmFAXmJoPZ3GMP8bR/sAnWfHG/5DLK1KqXC6nAI/lLbo2NUcTVGaG1XrRMr885MOy/sHagSIuXuPmHfpoT1fGHbLSeoWiUFkygOR9f1wVkVHR7fu8+aFLD49GVGpwOZoMtY4k+xuSaMiv9tLgqOsYZzoWOSw0YTOCIy9A0Jum8Vsn/TzL5KvLXIuuJJElmBEXyuJfNsHhyWnpe8122FJ/G1jMv4XsqmEeK/sWLzZeVVw4fucUq/kA82euEOD6ROKFraiemiCHd9578ots4RYIBqOKpAZF1nc5J5h8noEEvtdcDwOcL+qDWsnqKB4KLRRl9wV3VfVOWQC2s3Bv3f7Z90MEhXVNbf9ZKE4nAnzj6TICzbL4VaqXR9MEw==
    secret-key: AgAift9yVncy4iaKGG+9EN5tfRHVz0K6JKlziwQIaCFglPNGr8XCTRp/nRfnZ9JhAaG+mBAdiDAoLj4OSIsKVo+dKk+bBvBsUGm3eZklxcgtOj/yJdnzFjWaQKs1+BNd437HG/qnmzgpCmHRoNo+cxihcw66vqzJJnAeOvyVw/IwvEqi2TcE2PkEmlCqNrGN45ZOX7MN0jnmNPTWAQEJdmh5fU1IrLv88bz0wON7Jm59A55qHeScZ6F6BhY/AhE+1WCpRyPxsxsVVpCUorwM2bJYdvbDRWO+VXLCaA4wJ4zRpmjhCh9ELQNEx2U1r9Uqn/K2rN/Q6IAekNQueh+OkgccEdvIqMWt2gqmhdyfXRVHqCw5WV7G/dMpuNs3l20mG/ECVF2WApRR042h2VrImDAq4UzUAqaaeVc2tS9gwW5aIow2ezpi6wzOx9W5GIJfJpjcaWqb6Ql0JrinKiAeO3HeeklL7HP1VLg6RRjjf/db5N4gJWgSmQ/4y6kmO7uajfKd6FAbB3FhsFxPEeOGSHiqa+Rgt2XmF8ibvmjEVzdApOdDxCTGb+dHF9jdDjXlwoOhUUGlXKmmhQGrVTW0Rf9hXBH+T4vP/oyvY9P3ZVwF2TsIvZUhtqwMsxGAlBItCnJzLxEkHUuw5Sh0vSh9CNbitN7/XbWa7E84amuCSaYutcZWgyQ8gs1YmbRrWu9gqO+rNrUvDPExbw==
  template:
    metadata:
      name: spark-credentials
      namespace: spark
