---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: spark-credentials
  namespace: spark
spec:
  encryptedData:
    access-key: AgAAilhuGfA/JRJLzJS8x15k/FYj0WVuMfoLPexsHiY2whf0MUgz86NjGPeTZTgIXzFu3aEHCHkAUBTFTkn82UPbQITKPEIuks2CO0uNGgxmfuFK4J3CDVGCjTsBzb8MRvAySdpB1uJyyftXxz62qRmOHCwr/GZrfA34FV4iLAv78XAQQfB8zqC/m0FImrhNQy6tA+I3foKjsXt3SI726Jij1U3M6xFpcBGJwHZeYPiEntzBOf2QoB5Z8pItYX+gdsn2dbRxtIt/DMckpVD0mf3NAsOnFR5VPV5G9l9llWhcsOkZ0Ksksr+gr0stsjpqw23ZRYOaYINJUfbhL6evg1ThTCnVffRZAwglbL4AlhQpAe0Xw+DtjOqSuGGty7yhi3olFbgBZcaKrBe0143ygNeAcK66eTIW2l8tdu2gOCA+3+rTR5yDJGxPp5NhglsLBc6tYtPINN++VwMCTX41fY6ueR9o3C1U+HyRxvoecROEE/VKN1RChbqFZ8SzwzUNUPuM1E/m+qvg1+LTGdlhFazhj1gPpfGcVvvb1bZd6Hx94nw+a516P9jNj5RA3vtZLs7XCg25AbEi5/qQBAtEs+LBBRt8SMx7Wi87RtgoHIx40zdqAepeu9el8+rHtdJZgZJ8HDa4/NAOqIM1cLJXoO4pMbRmjArmYCaESV/d1dJV7o34xpDgLgjqWbPJcYCIz4cWKS/Edg==
    secret-key: AgCCWOa/4eCgTvk71u3UVzXMZ/IfMonafhE4zTqpwfkiu5iNA0wSd709Sgt1vcDB+ZjLncf7LZ7WGEBv9M8LOAEIE0FNzqGaKUXEvyY3P7hqDu6jVPN9DdJX2x7cwL8+htrmpXdV26zJpI/83UfZ19O/NnrViCf8XAqEBQ7whf/2t3qWZ38dwb36IzsZeleUN8iA1un+zy8V3tyxwVhtdI2LP44JBvCZtPMYn3okvg8NPwlTcUFxE0Rs7u7QIC42D1bhKemJsz7CL32g6D1r64nLLk6Ml/8hxUrt6yFherykwW8/8cXuwEJpzq2l4eXsucGm+xn28RM6BoBvoZCvulmpxceVGxCyGUrwVW/QZKIdG806G1ZnRqrdW8CMp2bg+gmALwca9OE7AMHjXHGTZjH+pRmkte3g7W679yS2IZEwc33yDNJ1X2ZkX6MI7o0RWh+ryzvt/3e/ksxBXFk0nvSkc6spcv+dUC7ggdOnERZq7xCL1OXV7B8UKeZlnY5FWV8YLwUYUR+jfEFUB6M77AlwjjqsKJqxBctwUe7qLjk/Mt2N+pyF+NMHVFPnalTNbx0Nj88jFVfHxHxSuQ3KXu83AiWsp4UEfn3+2zbraDAuJYdJqRjxpVCwC0w7Mt6McUgS5te/HdTqSSMtzpSd2gxo/Wbch/7bujN09B9h0ukxYIC/A3NPQ+NrDyJOK4P+3j0LDFS02BHHqQ==
  template:
    metadata:
      name: spark-credentials
      namespace: spark
