apiVersion: v1
kind: Service
metadata:
  name: nessie
  namespace: catalog
spec:
  selector:
    app: nessie
  ports:
  - name: api
    port: 19120
    targetPort: 19120
  - name: management
    port: 9000
    targetPort: 9000